export const header: string;
export const headerContainer: string;
export const headerRight: string;
export const headerLeft: string;
export const ul: string;
export const flex1: string;
export const ulright: string;
export const sec: string;
export const three: string;
